# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AbognCCtlgn 的博客
description: > # this means to ignore newlines until "baseurl:"
  基于 jekyll 的 <a href="https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages">Github Pages</a> 个人博客网站，记录与分享平时所遇到的问题及解决方案

#baseurl: "/matjek"
url: "https://abogncctlgn.github.io"
#permalink: /:year/:month/:day/:title
#repository: ShawnTeoh/matjek
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/abogncctlgn"
user: "AbognCCtlgn"
user_email: "779502449@qq.com"
#contact_url: "https://goo.gl/tVljbV"
#google_tracking_id: "UA-96359860-1"
#google_site_verification: "UA-96359860-1"
#disqus_shortname: "matjek"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
lang: zh_CN
permalink: /:year/:month/:day/:title
theme: jekyll-theme-slate
